# Generated by Django 2.2.7 on 2019-11-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191117_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='username',
        ),
        migrations.AddField(
            model_name='article',
            name='by',
            field=models.CharField(max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
