# Generated by Django 2.2.7 on 2019-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191117_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('title', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True)),
                ('score', models.IntegerField()),
                ('sentimentPolarity', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
